### ISSUE TITLE
`FileStream` now embeds `InputStream` by reference instead of pointer

### ISSUE THREAD

**Issue by keilin-anz** [antlr4-go/antlr#6]
Just mentioning in case this is a migration glitch from the recent repo split

What's odd is the documentation on pkg.go.dev is consistent with the old module, but the code is different

- Old docs: https://pkg.go.dev/github.com/antlr/antlr4/runtime/Go/antlr#FileStream
- Current docs: https://pkg.go.dev/github.com/antlr4-go/antlr#FileStream
- Current code: https://github.com/antlr4-go/antlr/commit/7d5ead3994bc5235c54b30001091d182ffb450ad#diff-c1424d6dba3446dfa4135b7c039dc823c191b7912792635ac63079ed8ed10c4eR16

**Comment by jimidle** [comment]
This is on purpose. The embedded by * was a mistake by the original author. You were looking at the wrong documentation.

https://pkg.go.dev/github.com/antlr4-go/antlr/v4
