### ISSUE TITLE
how to high performance reuse parser in latest version（v4.13.0）?

### ISSUE THREAD

**Issue by woisnow** [antlr4-go/antlr#8]
- in old version(github.com/antlr/antlr4/runtime/Go/antlr v0.0.0-20220415214452-44d87bc1d130) antlr 4.10.1; 
- first we use SLL mode with BailErrorStrategy, if err, we reuse parser with LL mode and defaultErrorStrategy, everything is ok.
-  but in latest version, we have two issue: 
- 1. second step (LL mode) would panic too; when we use code "parser.SetErr(nill)", it would not panic; 
- 2.  using SLL panic and fallback LL mode in latest version cost double time then old version; why?

```
is := antlr.NewInputStream(sql)
errorListener := NewErrorListener()
// setup lexer
lexer.SetInputStream(is)
lexer.RemoveErrorListeners()
stream := antlr.NewCommonTokenStream(lexer, antlr.TokenDefaultChannel)
// setup parser
parser.SetInputStream(stream)
parser.RemoveErrorListeners()
parser.SetErrorHandler(antlr.NewBailErrorStrategy())
// parse
var stmt antlr.ParseTree
func() {
parser.GetInterpreter().SetPredictionMode(antlr.PredictionModeSLL)
defer func() {
	if e := recover(); e != nil {
		fmt.Println(ctx, "parse by SLL failed")
                 // parser.SetErr(nil)  // need this code in latest version; but old version not need
		parser.AddErrorListener(errorListener)
		parser.SetErrorHandler(antlr.NewDefaultErrorStrategy())
		parser.GetInterpreter().SetPredictionMode(antlr.PredictionModeLL)
		stream.Seek(0)
                 // parser.SetInputStream(stream)   // need this code in latest version; but old version not need
		stmt = parser.QueryStmt()
	}
}()
stmt = parser.QueryStmt()
}()
```

**Comment by jimidle** [comment]
The old version of the runtime was broken and did not do all the work it is supposed to do when in LL mode and your grammar is a bad one. Hence now it does all the work and appears to be half the speed. In fact, your grammar is the issue here as it usually is in these case. DOn't use any of the grammars from PostiveTechnologies.

**Comment by woisnow** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我是姚亚楠，邮件已收到，我会尽快给您回复。
